version: '3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:admin@mysql:3306
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '4000:3000'
    volumes:
      - .:/usr/src/rails-todo
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
